[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "11"
[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
	  public, 
    no-transform'''

