[build]
publish = "dist"
command = "npm run generate"
[build.environment]
NODE_VERSION = "11"
[[headers]]
for = "*.html"
[headers.values]
cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
Content-Security-Policy = "default-src 'self' https://ahmedabdulaziz.com/ https://www.ahmedabdulaziz.com/ https://ahmedabdulaziz-com.disqus.com/"
X-Frame-Options = "DENY"
[[headers]]
for = "/*"
[headers.values]
cache-control = '''
    max-age=31536000,
	  public, 
    no-transform'''
Content-Security-Policy = "default-src 'self' https://ahmedabdulaziz.com/ https://www.ahmedabdulaziz.com/ https://media.giphy.com/ https://www.googletagmanager.com/ https://www.google-analytics.com/ https://ahmedabdulaziz-com.disqus.com/ https://c.disquscdn.com/ https://disqus.com/ https://referrer.disqus.com/; style-src 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ahmedabdulaziz-com.disqus.com/ https://www.googletagmanager.com/ https://www.google-analytics.com/ https://c.disquscdn.com/ https://disqus.com/ https://referrer.disqus.com/"
X-Frame-Options = "DENY"
