[build]
publish = "dist"
command = "npm run generate"
[build.environment]
NODE_VERSION = "11"
[[headers]]
for = "*.html"
[headers.values]
cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
Content-Security-Policy = "default-src 'self';"
X-Frame-Options = "DENY"
[[headers]]
for = "/*"
[headers.values]
cache-control = '''
    max-age=31536000,
	  public, 
    no-transform'''
Content-Security-Policy = "default-src 'self'; style-src 'unsafe-inline'; script-src 'self' 'unsafe-inline'"
X-Frame-Options = "DENY"
